version: '3'
services:
  api:
    image: fleact_api
    build:
        context: ./api/
        dockerfile: Dockerfile_api
    env_file:
        - .env
    ports:
        - '5000:5000'
  web:
    image: fleact_web
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - '80:80'
    depends_on:
      - api
