version: '3'
services:
  backend:
    image: fleact_backend
    build:
        context: ./api/
        dockerfile: Dockerfile
    env_file:
        - .env
    ports:
        - '5000:5000'
  frontend:
    image: fleact_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
